#Database
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: til21
    password: '!Xlfxndnjs21'

    #Connection Pool
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 10

  #JPA
  jpa:
    database: POSTGRESQL
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    open-in-view: false

    generate-ddl: true
    hibernate:
      ddl-auto: validate

    show-sql: true
    properties:
      format_sql: true
      non_contextual: true

  #Liquibase
  liquibase:
    change-log: classpath:/liquibase/changelog-master.yaml
#    change-log: classpath:/liquibase/changelogs-xml/changelog-master.xml
